---
apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-service-config
  namespace: togglemaster
data:
  PORT: "8001"
  DATABASE_URL: "postgres://toggleadmin:XEre2477()@togglemaster-prod-auth-db.c6z0wmwy6t8u.us-east-1.rds.amazonaws.com:5432/authdb?sslmode=disable"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: flag-service-config
  namespace: togglemaster
data:
  PORT: "8002"
  DATABASE_URL: "postgres://toggleadmin:XEre2477()@togglemaster-prod-flag-db.c6z0wmwy6t8u.us-east-1.rds.amazonaws.com:5432/flagdb?sslmode=disable"
  AUTH_SERVICE_URL: "http://auth-service:8001"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: targeting-service-config
  namespace: togglemaster
data:
  PORT: "8003"
  DATABASE_URL: "postgres://toggleadmin:XEre2477()@togglemaster-prod-targeting-db.c6z0wmwy6t8u.us-east-1.rds.amazonaws.com:5432/targetingdb?sslmode=disable"
  REDIS_URL: "redis://togglemaster-prod-redis.2xbxhf.0001.use1.cache.amazonaws.com:6379"
  AUTH_SERVICE_URL: "http://auth-service:8001"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: evaluation-service-config
  namespace: togglemaster
data:
  PORT: "8004"
  REDIS_URL: "redis://togglemaster-prod-redis.2xbxhf.0001.use1.cache.amazonaws.com:6379"
  AWS_SQS_URL: "https://sqs.us-east-1.amazonaws.com/990857982395/togglemaster-prod-evaluation-events"
  AWS_REGION: "us-east-1"
  AUTH_SERVICE_URL: "http://auth-service:8001"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: analytics-service-config
  namespace: togglemaster
data:
  PORT: "8005"
  AWS_SQS_URL: "https://sqs.us-east-1.amazonaws.com/990857982395/togglemaster-prod-evaluation-events"
  AWS_DYNAMODB_TABLE: "ToggleMasterAnalytics"
  AWS_REGION: "us-east-1"
